export const PERMISSIONS = {
    // Administration
    READ_LOGO_MANAGEMENT: 1,
    WRITE_LOGO_MANAGEMENT: 2,

    READ_BANNER_MANAGEMENT: 3,
    WRITE_BANNER_MANAGEMENT: 4,

    READ_LERG_MANAGEMENT: 5,
    WRITE_LERG_MANAGEMENT: 6,

    READ_CDR_SERVER_MANAGEMENT: 7,
    WRITE_CDR_SERVER_MANAGEMENT: 8,

    CDR_IMPORT_HISTORY: 9,
    CDR_LOG: 10,

    READ_LRN_MANAGEMENT: 11,
    WRITE_LRN_MANAGEMENT: 12,

    // Client Manangement
    READ_CUSTOMERS: 101,
    WRITE_CUSTOMERS: 102,

    READ_ROLES: 103,
    WRITE_ROLES: 104,

    READ_USERS: 105,
    WRITE_USERS: 106,

    // Vendor Management
    READ_VENDORS: 201,
    WRITE_VENDORS: 202,

    READ_VENDOR_RATES: 203,
    WRITE_VENDOR_RATES: 204,

    VENDOR_COMPARATION: 205,

    // Number Management
    READ_BUY_NUMBERS: 301,
    WRITE_BUY_NUMBERS: 302,

    READ_CUSTOMER_NUMBERS: 303,
    WRITE_CUSTOMER_NUMBERS: 304,

    READ_TFN_NUMBERS: 305,
    WRITE_TFN_NUMBERS: 306,

    READ_DID_NUMBERS: 307,
    WRITE_DID_NUMBERS: 308,

    // Billing Management
    AUTO_GENERATE_STATEMENT: 401,
    CREATE_BILLING_STATEMENT: 405,
    VIEW_BILLING_STATEMENT: 410,
    TAX_MANAGEMENT: 420,
    RERATE_CALLS: 430,
    AUTO_GENERATE_INVOICE: 440,
    CUSTOMER_PAYMENT: 450,
    STATEMENT_ACCOUNT: 460,
}

export const CUSTOMER_PERMISSIONS = [
    PERMISSIONS.READ_LOGO_MANAGEMENT, PERMISSIONS.READ_BANNER_MANAGEMENT,
    PERMISSIONS.READ_CUSTOMER_NUMBERS, PERMISSIONS.WRITE_CUSTOMER_NUMBERS, PERMISSIONS.READ_TFN_NUMBERS, PERMISSIONS.WRITE_TFN_NUMBERS,
    PERMISSIONS.CREATE_BILLING_STATEMENT, PERMISSIONS.VIEW_BILLING_STATEMENT,
]

export const VENDOR_PERMISSIONS = [
    PERMISSIONS.READ_LOGO_MANAGEMENT, PERMISSIONS.READ_BANNER_MANAGEMENT,
    PERMISSIONS.READ_CUSTOMER_NUMBERS, PERMISSIONS.WRITE_CUSTOMER_NUMBERS, PERMISSIONS.READ_TFN_NUMBERS, PERMISSIONS.WRITE_TFN_NUMBERS,
    PERMISSIONS.CREATE_BILLING_STATEMENT, PERMISSIONS.VIEW_BILLING_STATEMENT,
]
